lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - assets/multiqc_config.yaml
    - bin/scrape_software_versions.py
    - CODE_OF_CONDUCT.md
    - docs/README.md
    - .gitignore
  files_exist:
    - assets/nf-core-qbic-pipelines/cellranger_logo.png
    - docs/images/nf-core-qbic-pipelines/cellranger_logo.png
  actions_ci: False
  nextflow_config: False
